// Expo config plugin for `react-native-key-command` (SPEC-V2 §11 native hardware-keyboard
// shortcuts). Why this file exists at all: the library has no Expo config plugin — confirmed by
// listing the published package, no `plugin/` or `app.plugin.js` — and its README documents manual
// `AppDelegate.m` edits. This project uses CNG (`ios/` is gitignored, regenerated by
// `expo prebuild`), so a one-time hand-edit would be silently wiped on the next prebuild; this
// plugin reapplies the same two edits every time, idempotently.
//
// Two mods, both required for the library to actually deliver `UIKeyCommand` events:
//
//   1. AppDelegate — this project's template is Swift (`ios/ExceedBox/AppDelegate.swift`), not the
//      Objective-C template the library's README shows, so the snippet is translated by hand:
//        - `import UIKit` (for `UIKeyCommand`)
//        - `override var keyCommands: [UIKeyCommand]?` and `@objc func handleKeyCommand(_:)` on the
//          `AppDelegate` class, forwarding to `HardwareShortcuts.sharedInstance()`.
//      This works because `ExpoAppDelegate` (what this project's `AppDelegate` extends) is declared
//      `open class ExpoAppDelegate: UIResponder, UIApplicationDelegate`
//      (node_modules/expo/ios/AppDelegates/ExpoAppDelegate.swift) — being a `UIResponder` is exactly
//      what makes the app delegate a legal link in UIKit's key-command responder chain, which is why
//      the upstream ObjC pattern (`@implementation AppDelegate ... - (NSArray *)keyCommands ...`)
//      translates directly to a Swift `override`.
//
//   2. The Swift bridging header — this project's Swift AppDelegate template already ships one
//      (`ios/ExceedBox/ExceedBox-Bridging-Header.h`, wired via the `SWIFT_OBJC_BRIDGING_HEADER`
//      build setting; standard for any Expo/RN app with a Swift AppDelegate, not specific to this
//      plugin) — add `#import <HardwareShortcuts.h>` so the Objective-C class the library exports is
//      visible to Swift. No bridging header would mean `HardwareShortcuts` is simply an unknown
//      identifier to the Swift compiler.
//
// Autolinking (the pod itself, `react-native-key-command.podspec`) needs no plugin — Expo's
// standard node_modules/podspec autolinking picks it up from being in package.json alone, same as
// every other native dependency in this project.
//
// Both mods use `mergeContents`, which tags its inserted block with a hash-checked header comment,
// so re-running `expo prebuild` repeatedly does not duplicate the edits.

const { withAppDelegate, withDangerousMod, IOSConfig } = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');
const fs = require('fs');
const path = require('path');

const TAG = 'react-native-key-command';

function withKeyCommandAppDelegate(config) {
  return withAppDelegate(config, (config) => {
    const { modResults } = config;

    if (modResults.language !== 'swift') {
      // This project's AppDelegate is Swift today (SDK 57 / RN 0.86 template). If a future prebuild
      // regenerates an Objective-C AppDelegate instead, this plugin's Swift-specific insertion would
      // silently do nothing useful — fail loudly instead of shipping a build with dead shortcuts.
      throw new Error(
        `withKeyCommand: expected a Swift AppDelegate but found "${modResults.language}". ` +
          'Update plugins/withKeyCommand.js with an Objective-C insertion (see react-native-key-command\'s README for the .m snippet) before prebuilding.'
      );
    }

    let contents = modResults.contents;

    contents = mergeContents({
      src: contents,
      newSrc: 'import UIKit',
      tag: `${TAG}-import`,
      anchor: /^import React$/m,
      offset: 1,
      comment: '//',
    }).contents;

    contents = mergeContents({
      src: contents,
      newSrc: [
        '  // react-native-key-command (SPEC-V2 §11): UIKeyCommand only reaches the app once the app',
        "  // delegate — a UIResponder here — implements these two overrides. Swift translation of the",
        "  // library README's Objective-C AppDelegate.m snippet; see plugins/withKeyCommand.js.",
        '  override var keyCommands: [UIKeyCommand]? {',
        '    return HardwareShortcuts.sharedInstance().keyCommands as? [UIKeyCommand]',
        '  }',
        '',
        '  @objc func handleKeyCommand(_ keyCommand: UIKeyCommand) {',
        '    HardwareShortcuts.sharedInstance().handleKeyCommand(keyCommand)',
        '  }',
      ].join('\n'),
      tag: `${TAG}-methods`,
      anchor: /class AppDelegate: ExpoAppDelegate \{/,
      offset: 1,
      comment: '//',
    }).contents;

    modResults.contents = contents;
    return config;
  });
}

function withKeyCommandBridgingHeader(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const sourceRoot = IOSConfig.Paths.getSourceRoot(config.modRequest.projectRoot);
      const headerPath = path.join(sourceRoot, `${path.basename(sourceRoot)}-Bridging-Header.h`);

      if (!fs.existsSync(headerPath)) {
        throw new Error(
          `withKeyCommand: expected a Swift bridging header at ${headerPath} (this project's Swift ` +
            'AppDelegate template ships one) but it was not found. Update plugins/withKeyCommand.js.'
        );
      }

      const src = fs.readFileSync(headerPath, 'utf8');
      const merged = mergeContents({
        src,
        newSrc: '#import <HardwareShortcuts.h>',
        tag: TAG,
        // The template header is exactly three `//` comment lines and nothing else; anchoring on
        // the first of them and offsetting past all three appends after the boilerplate instead of
        // splitting it.
        anchor: /^\/\//,
        offset: 3,
        comment: '//',
      });
      fs.writeFileSync(headerPath, merged.contents);
      return config;
    },
  ]);
}

module.exports = function withKeyCommand(config) {
  config = withKeyCommandAppDelegate(config);
  config = withKeyCommandBridgingHeader(config);
  return config;
};
