import { createContext, useContext, useEffect, useRef } from 'react';

/**
 * SPEC v2 §11 hardware-keyboard shortcuts.
 *
 * Delivery mechanism, on both platforms this app ships to today:
 * - **Web** (`expo start --web`, or any build embedding a web view): the DOM `keydown` event,
 *   listened to once at the root by `KeyboardShortcutsProvider`.
 * - **iOS/iPadOS**: `UIKeyCommand`, bridged via the native module `react-native-key-command`
 *   (`KeyboardShortcutsProvider` loads it, parses each registered combo into the library's
 *   `{input, modifierFlags}` shape via `parseComboForNative` below, and forwards matching native
 *   `onKeyCommand` events to the same handler registry web uses). The library ships no Expo config
 *   plugin — `plugins/withKeyCommand.js` supplies the `AppDelegate`/bridging-header edits it needs
 *   under this project's CNG setup (`ios/` is gitignored and regenerated by `expo prebuild`).
 * - **Android**: intentionally still a no-op. The library also supports Android, but that requires
 *   its own `MainActivity` edit (see the library's README) and this project's SPEC-V2 §11 ask is
 *   specifically iPadOS — left unbound rather than guessed at and shipped untested. This matches
 *   this hook's pre-existing behaviour on Android (no regression).
 *
 * Every combo in the SPEC §11 set — `mod+k`, `mod+1`…`mod+6`, `mod+n`, `mod+f`, `escape`,
 * `arrowup`/`arrowdown`, `enter`, `mod+enter` — has a real `UIKeyCommand` equivalent (confirmed
 * against `react-native-key-command`'s native constants: `keyInputEscape`, `keyInputEnter`,
 * `keyInputUpArrow`/`keyInputDownArrow`, `keyModifierCommand`, all present since the library wraps
 * long-stable `UIKeyCommand` API). Nothing in this app's shortcut set needs to be left unbound on
 * iPadOS for a hardware-delivery reason — see the navigation/screens' own comments for which of
 * these have an actual on-screen action wired to them today vs. registered-but-unconsumed.
 *
 * Combo syntax: `"mod+k"`, `"mod+1"`, `"escape"`, `"arrowup"`, `"enter"`, `"mod+enter"` — "mod" means
 * Cmd on Mac/iPadOS and Ctrl elsewhere, matching `e.metaKey || e.ctrlKey`. Keys are lower-cased.
 */

export type ShortcutHandler = (e: KeyboardEvent) => void;

export interface KeyboardShortcutsRegistry {
  register: (combo: string, handler: ShortcutHandler) => () => void;
}

export const KeyboardShortcutsContext = createContext<KeyboardShortcutsRegistry | null>(null);

export function normalizeCombo(e: KeyboardEvent): string {
  const parts: string[] = [];
  if (e.metaKey || e.ctrlKey) parts.push('mod');
  if (e.shiftKey) parts.push('shift');
  if (e.altKey) parts.push('alt');
  parts.push(e.key.toLowerCase());
  return parts.join('+');
}

/** What `parseComboForNative` resolves a combo string to for `react-native-key-command`. */
export interface NativeKeyCommandDescriptor {
  input: string;
  modifierFlags: number;
}

/**
 * Translates this hook's combo syntax (`"mod+k"`, `"escape"`, `"mod+enter"`, ...) into the
 * `{input, modifierFlags}` shape `react-native-key-command`'s `registerKeyCommands`/`eventEmitter`
 * use, using the *native* constants the library's own `getConstants()` returns at runtime (never
 * hardcoded numbers — `UIKeyModifierFlags`/`UIKeyInput*` values are Apple's, not ours to guess).
 *
 * Returns `null` for a combo this platform's native constants can't express (none of this app's
 * SPEC §11 combos hit that path today — see this file's header — but a future screen registering
 * something odd degrades to "native no-op, web still works" rather than throwing or guessing).
 */
export function parseComboForNative(
  combo: string,
  constants: Record<string, string | number>
): NativeKeyCommandDescriptor | null {
  const parts = combo.toLowerCase().split('+');
  let modifierFlags = 0;
  let key: string | undefined;

  for (const part of parts) {
    switch (part) {
      case 'mod':
        modifierFlags |= Number(constants.keyModifierCommand ?? 0);
        break;
      case 'shift':
        modifierFlags |= Number(constants.keyModifierShift ?? 0);
        break;
      case 'alt':
        modifierFlags |= Number(constants.keyModifierOption ?? 0);
        break;
      case 'ctrl':
        modifierFlags |= Number(constants.keyModifierControl ?? 0);
        break;
      default:
        key = part;
    }
  }
  if (!key) return null;

  const SPECIAL_INPUTS: Record<string, string | number | undefined> = {
    escape: constants.keyInputEscape,
    arrowup: constants.keyInputUpArrow,
    arrowdown: constants.keyInputDownArrow,
    arrowleft: constants.keyInputLeftArrow,
    arrowright: constants.keyInputRightArrow,
    enter: constants.keyInputEnter,
  };

  const resolved = key in SPECIAL_INPUTS ? SPECIAL_INPUTS[key] : key;
  if (resolved === undefined) return null;

  return { input: String(resolved), modifierFlags };
}

/**
 * Registers `handler` for `combo` while the calling component is mounted (and `enabled` is true).
 * Safe to call even when no `KeyboardShortcutsProvider` is mounted (e.g. in tests), off web with no
 * native module linked yet, or on Android — it simply never fires. Screens outside this task's
 * ownership (src/screens/*) can adopt this directly:
 * `useKeyboardShortcut('mod+f', () => searchInputRef.current?.focus())`.
 */
export function useKeyboardShortcut(combo: string, handler: ShortcutHandler, enabled = true): void {
  const ctx = useContext(KeyboardShortcutsContext);
  const handlerRef = useRef(handler);
  handlerRef.current = handler;

  useEffect(() => {
    if (!ctx || !enabled) return undefined;
    return ctx.register(combo, (e) => handlerRef.current(e));
  }, [ctx, combo, enabled]);
}
